
# Данжи
dungeons:
  grim_spirit_dungeon:
    name: "Grim Spirit Dungeon"
    enter_in_distance: 2
    enter_in_dungeon: "world -47.5 115 9.5 0 0"
    enter_out_dungeon: "world -57.5 114 9.5 90 0"
    party_start: "world -3.5 114 9.5 0 0"
    party_settings: "world 7.5 114 9.5 0 0"



# Команды других плагинов, которые необходимы для запуска
commands:
  # Команда для имитации эффекта затемнения
  extinction: "screeneffect fullscreen BLACK 20 15 20 nofreeze %player%"

  # Команда для запуска данжа
  play: "md play Dungeon_Test %player%"

  # Команда для выхода из данжа
  leave: "md leave"



# Значения периодов (в тиках)
periods:
  # Период выполнения команды, после потемнения
  extinction: 25
  # Период кулдауна у уведомления всем о приглашении
  notice_invitation: 6000
  # Период кулдауна у плиглашения определенного игрока
  send_invite: 1200



# Звуки в используемые в плагине (<Название звука> <Тембр (pitch)> <Громкость (volume)>)
sounds:
  # Нажатие на кнопку
  button_click: "ps_sounds:ui.click_normal 1 100"
  # Переход в другую менюшку
  transition_click: "ps_sounds:ui.button_press 1 100"
  # Закрытие менюшки
  menu_close: "ps_sounds:ui.click_dead 1 100"



# Предметы
items:
  # Предмет кнопки для закрытия меню
  menu_close:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#FA2F2E>Закрыть"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Закрыть меню"

  # Предметы кнопок, отправка приглашения всем игрокам и кулдаун, после отправки
  party_all_invitation_use:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Уведомление для всех"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Отправить приглашение в общий чат"

  # Предметы кнопок для переключения между публичным и пати чатами
  open_party_chat:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Выбран чат: <white>Публичный чат"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Включить чат пати"
  open_public_chat:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Выбран чат: <#65f0f9>Чат пати"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Включить публичный чат"

  # Предмет кнопки для выхода игрока из пати
  party_leave:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#FA2F2E>Выйти"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Выйти из пати"

  # Предмет кнопки, приглашение игрока
  party_invite_leader:
    material: FEATHER
    custom_model_data: 10005
    name: "<!italic><gray>Пустой слот"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Пригласить игрока"
  party_invite_player:
    material: FEATHER
    custom_model_data: 10005
    name: "<!italic><gray>Пустой слот"
    lore:

  # Предметы кнопок, готов (ready), не готов игрок в пати (not_ready) или слот с игроком пустой (undefined)
  player_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Статус: <#94FF1A>Готов"
    lore:
  player_not_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Статус: <#FA2F2E>Не готов"
    lore:
  player_undefined:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Статус: <gray>Неопределенно"
    lore:

  # Предметы кнопок, функциональные кнопки (готов, отмена, старт)
  func_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Готов"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Нажмите, если готовы"
  func_cancel:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#FA2F2E>Отмена"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Отменить готовность"
  func_start:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Старт"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Начать подземелье"


  # Предметы кнопок для менюшки при выборе одиночки или коорператива
  start_single_player:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Одиночное прохождение данжа"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Начать прохождени данжа"
  start_multiplayer_player:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Кооперативное прохождение данжа"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Создать пати"
  start_return_back:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Вернуться назад"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Вернуться ко входу в данж"



  # Предметы кнопок для менюшки при приглашении игроков или друзей в пати
  prev_page_on:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Предыдущая страница"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Перейти к предыдующей странице"
  prev_page_off:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><gray>Предыдущей страницы нет"
    lore:
  next_page_on:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Следующая страница"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Перейти к следующей странице"
  next_page_off:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><gray>Следующей страницы нет"
    lore:
  return_back:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#FA2F2E>Вернуться назад"
    lore:




# Предметы с плейсхолдерами
items_placeholders:
  # Предметы кнопок, используемые при отображении игроков
  # Отображение головы лидера для лидера
  head_leader_for_leader:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:
  # Отображение головы лидера для игроков
  head_leader_for_player:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:
  # Отображение головы игроков для лидера
  head_player_for_leader:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:
      - "<!italic><#fcd294>[SHIFT + ЛКМ] <gray>- Поставить на место лидера"
      - "<!italic><#fcd294>[SHIFT + ПКМ] <gray>- Кикнуть из пати"
  # Отображение головы игроков для игроков
  head_player_for_player:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:


  # Предмет кнопки, используемый при отображении кулдауна, после приглашения всех
  party_all_invitation_not_use:
    placeholders:
      name:
      lore:
        - "%time%"
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><gray>Уведомление для всех"
    lore:
      - "<!italic><gray>Будет доступно через: <dark_gray>%time%"

  # Предметы кнопок для переключения между друзьями и игроками
  friends_pages:
    placeholders:
      name:
      lore:
        - "%amount%"
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Только друзья"
    lore:
      - "<!italic><gray>Друзей: <white>%amount%"
      - ""
      - "<!italic><#fcd294>[ЛКМ] <gray>- Показать только друзей"
  players_pages:
    placeholders:
      name:
      lore:
        - "%amount%"
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Все игроки"
    lore:
      - "<!italic><gray>Игроков: <white>%amount%"
      - ""
      - "<!italic><#fcd294>[ЛКМ] <gray>- Показать всех игроков"
  head_player_in_party_players:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Пригласить игрока"

