
# Команды других плагинов, которые необходимы для запуска
commands:
  # Команда для имитации эффекта затемнения
  extinction: "screeneffect fullscreen BLACK 20 10 20 nofreeze %player%"

  # Команда для запуска данжа
  play: "md play Dungeon_Test %player%"

  # Команда для выхода из данжа
  leave: "md leave"



# Координаты
points:
  # Координата с местом входа в подземелье
  enter_dungeon: "world -53.5 115 9.5 90 0"



# Предметы
items:
  # Предмет кнопки для закрытия меню
  menu_close:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#FA2F2E>Закрыть"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Закрыть меню"

  # Предметы кнопок, отправка приглашения всем игрокам и кулдаун, после отправки
  party_all_invitation_use:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Уведомление для всех"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Отправить приглашение в общий чат"

  # Предметы кнопок для переключения между публичным и пати чатами
  open_party_chat:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Выбран чат: <white>Публичный чат"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Включить чат пати"
  open_public_chat:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Выбран чат: <#65f0f9>Чат пати"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Включить публичный чат"

  # Предмет кнопки для выхода игрока из пати
  party_leave:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#FA2F2E>Выйти"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Выйти из пати"

  # Предмет кнопки, приглашение игрока
  party_invite:
    material: FEATHER
    custom_model_data: 10005
    name: "<!italic><#94FF1A>Пригласить игрока"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Выбрать игрока"

  # Предметы кнопок, готов (ready), не готов игрок в пати (not_ready) или слот с игроком пустой (undefined)
  player_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Статус: <#94FF1A>Готов"
    lore:
  player_not_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Статус: <#FA2F2E>Не готов"
    lore:
  player_undefined:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#f9883a>Статус: <gray>Неопределенно"
    lore:

  # Предметы кнопок, функциональные кнопки (готов, отмена, старт)
  func_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Готов"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Нажмите, если готовы"
  func_cancel:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#FA2F2E>Отмена"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Отменить готовность"
  func_start:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><#94FF1A>Старт"
    lore:
      - "<!italic><#fcd294>[ЛКМ] <gray>- Начать подземелье"



# Предметы с плейсхолдерами
items_placeholders:
  # Предметы кнопок, используемые при отображении игроков
  # Отображение головы лидера для лидера
  head_leader_for_leader:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:
  # Отображение головы лидера для игроков
  head_leader_for_player:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:
  # Отображение головы игроков для лидера
  head_player_for_leader:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:
      - "<!italic><#fcd294>[SHIFT + ЛКМ] <gray>- Поставить на место лидера"
      - "<!italic><#fcd294>[SHIFT + ПКМ] <gray>- Кикнуть из пати"
  # Отображение головы игроков для игроков
  head_player_for_player:
    placeholders:
      name:
        - "%player%"
      lore:
    material: PLAYER_HEAD
    custom_model_data: 1
    name: "<!italic><#f9883a>Игрок: <white>%player%"
    lore:


  # Предмет кнопки, используемый при отображении кулдауна, после приглашения всех
  party_all_invitation_not_use:
    placeholders:
      name:
      lore:
        - "%time%"
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><gray>Уведомление для всех"
    lore:
      - "<!italic><gray>Будет доступно через: <dark_gray>%time%"

