
# Команда для имитации эффекта затемнения
command_extinction: "screeneffect fullscreen BLACK 20 10 20 nofreeze %player%"

# Предметы
items:
  # Предмет кнопки для закрытия меню
  menu_close:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><red>Закрыть"
    lore:
      - "<!italic><gray>[ЛКМ] - Закрыть меню"

  # Предмет кнопки, отправка приглашения всем желающим
  party_all_invitation:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><green>Пригласить всех"
    lore:
      - "<!italic><gray>[ЛКМ] - Отправить сообщение о приглашении в общий чат"

  # Предметы кнопок для переключения между публичным и пати чатами
  open_party_chat:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><white>Выбран чат: <gray>Публичный чат"
    lore:
      - "<!italic><gray>[ЛКМ] - Включить чат пати"
  open_public_chat:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><white>Выбран чат: <#af5dcf>Чат пати"
    lore:
      - "<!italic><gray>[ЛКМ] - Включить публичный чат"

  # Предмет кнопки для выхода игрока из пати
  party_leave:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><red>Выйти"
    lore:
      - "<!italic><gray>[ЛКМ] - Выйти из пати"

  # Предмет кнопки, приглашение игрока
  party_invite:
    material: FEATHER
    custom_model_data: 10005
    name: "<!italic><green>Пригласить игрока"
    lore:
      - "<!italic><gray>[ЛКМ] - Выбрать игрока"

  # Предметы кнопок, готов (ready), не готов игрок в пати (not_ready) или слот с игроком пустой (undefined)
  player_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><gray>Статус: <green>Готов"
    lore:
  player_not_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><gray>Статус: <red>Не готов"
    lore:
  player_undefined:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><gray>Статус: Неопределенно"
    lore:

  # Предметы кнопок, функциональные кнопки (готов, отмена, старт)
  func_ready:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><green>Готов"
    lore:
      - "<!italic><gray>[ЛКМ] - Нажмите, если готовы"
  func_cancel:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><red>Отмена"
    lore:
      - "<!italic><gray>[ЛКМ] - Отменить готовность"
  func_start:
    material: FEATHER
    custom_model_data: 10004
    name: "<!italic><green>Старт"
    lore:
      - "<!italic><gray>[ЛКМ] - Начать подземелье"


# Координаты
points:
  # Координата с местом входа в подземелье
  enter_dungeon: "world -53.5 115 9.5 90 0"
