name: DungeonPS
version: '1.0-SNAPSHOT'
main: me.vovari2.dungeonps.DPS
api-version: 1.19
commands:
  dungeonps:
    description: "Use to control plugin DungeonPS"
    permission: "dungeonps.admin"
    aliases:
      - "dps"

depend:
  - "Parties"


